# -*- coding: utf-8 -*-
"""Laboratório3.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aBWM78xkPP_v7F7qQCEACB9QpkI2qy7s
"""

import warnings, requests, zipfile, io

warnings.filterwarnings('ignore')

import pandas as pd

from scipy.io import arff

f_zip = 'http://archive.ics.uci.edu/ml/machine-learning-databases/00212/vertebral_column_data.zip'
r = requests.get(f_zip, stream=True)

Vertebral = zipfile.ZipFile(io.BytesIO(r.content))
Vertebral.extractall()

data = arff.loadarff('collmn_3C_weka.arff')
df = pd.DataFrame(data[0])
df.head()